name: advanced_chips_input
description: Customizable text input widget for creating chips from the text.

version: 0.1.4
repository: https://github.com/EduardoYamauchi/advanced_chips_input

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
