name: advanced_chips_input
description: A Flutter package that provides a customizable text input widget for creating chips from 
  the text. It supports chip deletion, input validation, and a variety of customization options such
  as container decoration, chip text style, and delete icon. Whether you want to create a list of 
  tags, mentions, or any other list of items, this package helps you create a beautiful and 
  functional chip input field.

version: 0.1.0
repository: https://github.com/EduardoYamauchi/advanced_chips_input

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
